name: example
description: A Flutter example project to demonstrate the custom_dialog_package functionality.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  confirm_dialog: ^1.0.3
  flutter:
    sdk: flutter
  # Remove this line:
  confirmation_dialog_package:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
