name: example
description: A Flutter example project to demonstrate the animated_confirm_dialog functionality.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_confirm_dialog:
    path: ../ # This should point to the renamed package's directory.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
