name: confirmation_dialog_package
description: A Flutter package for customizable confirmation dialogs with optional 3D flip animations and a modern UI.
version: 0.0.1
homepage: https://github.com/MilakeSuraj/confirmation_dialog_package
issue_tracker: https://github.com/MilakeSuraj/confirmation_dialog_package/issues

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

keywords:
  - flutter
  - dialog
  - confirmation-dialog
  - animations
  - ui
  - logout-button
  - button
  - confirmation-button
  - animated-button
  - confirmation-dialog
  - popup
  - popupbox
